version: '2'
services:
  mqtt-infoscreens:
    image: toke/mosquitto
    ports:
      - '1882:9001'
      - '1883:1883'
  infoscreens:
    image: cbase/infoscreens
    ports:
      - '8080:8080'
    links:
      - mqtt-infoscreens
    volumes:
      - ./dist:/var/infoscreens/dist
      - ./videos:/var/infoscreens/videos
      - ./pictures:/var/infoscreens/pictures
