name: build and push docker container

on:
  push:
    branches:
      - master
      - gh-actions

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       include:
         - target: x86
           docker-image: cbase/infoscreens
           compose-file: docker-compose.yml
           docker-file: Dockerfile
             #         - target: raspberrypi3
             #           docker-image: cbase/raspberrypi3-infoscreens
             #           compose-file: docker-compose-raspberrypi3.yml
             #           docker-file: Dockerfile-raspberrypi3

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.docker-file }}
          push: true
          platforms: linux/amd64,linux/arm
          tags: |
            ${{ matrix.docker-image }}:latest
            ${{ matrix.docker-image }}:${{ github.sha }}

